export const PaystackCurrencies = [
    { currency: 'USD', currency_symbol: '$', multiplier: 100, type: 'Paystack' },
    { currency: 'AED', currency_symbol: 'د.إ', multiplier: 100, type: 'Paystack' },
    { currency: 'AFN', currency_symbol: '؋', multiplier: 100, type: 'Paystack' },
    { currency: 'ALL', currency_symbol: 'L', multiplier: 100, type: 'Paystack' },
    { currency: 'AMD', currency_symbol: '֏', multiplier: 100, type: 'Paystack' },
    { currency: 'ANG', currency_symbol: 'ƒ', multiplier: 100, type: 'Paystack' },
    { currency: 'AOA', currency_symbol: 'Kz', multiplier: 100, type: 'Paystack' },
    { currency: 'ARS', currency_symbol: '$', multiplier: 100, type: 'Paystack' },
    { currency: 'AUD', currency_symbol: '$', multiplier: 100, type: 'Paystack' },
    { currency: 'AWG', currency_symbol: 'ƒ', multiplier: 100, type: 'Paystack' },
    { currency: 'AZN', currency_symbol: '₼', multiplier: 100, type: 'Paystack' },
    { currency: 'BAM', currency_symbol: 'BAM', multiplier: 100, type: 'Paystack' },
    { currency: 'BBD', currency_symbol: '$', multiplier: 100, type: 'Paystack' },
    { currency: 'BDT', currency_symbol: '৳', multiplier: 100, type: 'Paystack' },
    { currency: 'BGN', currency_symbol: 'лв', multiplier: 100, type: 'Paystack' },
    { currency: 'BIF', currency_symbol: 'Fr', multiplier: 1, type: 'Paystack' },
    { currency: 'BMD', currency_symbol: '$', multiplier: 100, type: 'Paystack' },
    { currency: 'BND', currency_symbol: '$', multiplier: 100, type: 'Paystack' },
    { currency: 'BOB', currency_symbol: 'Bs.', multiplier: 100, type: 'Paystack' },
    { currency: 'BRL', currency_symbol: 'R$', multiplier: 100, type: 'Paystack' },
    { currency: 'BSD', currency_symbol: '$', multiplier: 100, type: 'Paystack' },
    { currency: 'BWP', currency_symbol: 'P', multiplier: 100, type: 'Paystack' },
    { currency: 'BZD', currency_symbol: '$', multiplier: 100, type: 'Paystack' },
    { currency: 'CAD', currency_symbol: '$', multiplier: 100, type: 'Paystack' },
    { currency: 'CDF', currency_symbol: 'Fr', multiplier: 100, type: 'Paystack' },
    { currency: 'CHF', currency_symbol: 'Fr', multiplier: 100, type: 'Paystack' },
    { currency: 'CLP', currency_symbol: '$', multiplier: 1, type: 'Paystack' },
    { currency: 'CNY', currency_symbol: '¥', multiplier: 100, type: 'Paystack' },
    { currency: 'COP', currency_symbol: '$', multiplier: 100, type: 'Paystack' },
    { currency: 'CRC', currency_symbol: '₡', multiplier: 100, type: 'Paystack' },
    { currency: 'CVE', currency_symbol: '$', multiplier: 100, type: 'Paystack' },
    { currency: 'CZK', currency_symbol: 'Kč', multiplier: 100, type: 'Paystack' },
    { currency: 'DJF', currency_symbol: 'Fr', multiplier: 1, type: 'Paystack' },
    { currency: 'DKK', currency_symbol: 'kr', multiplier: 100, type: 'Paystack' },
    { currency: 'DOP', currency_symbol: '$', multiplier: 100, type: 'Paystack' },
    { currency: 'DZD', currency_symbol: 'د.ج', multiplier: 100, type: 'Paystack' },
    { currency: 'EGP', currency_symbol: '£', multiplier: 100, type: 'Paystack' },
    { currency: 'ETB', currency_symbol: 'Br', multiplier: 100, type: 'Paystack' },
    { currency: 'EUR', currency_symbol: '€', multiplier: 100, type: 'Paystack' },
    { currency: 'FJD', currency_symbol: '$', multiplier: 100, type: 'Paystack' },
    { currency: 'FKP', currency_symbol: '£', multiplier: 100, type: 'Paystack' },
    { currency: 'GBP', currency_symbol: '£', multiplier: 100, type: 'Paystack' },
    { currency: 'GEL', currency_symbol: '₾', multiplier: 100, type: 'Paystack' },
    { currency: 'GIP', currency_symbol: '£', multiplier: 100, type: 'Paystack' },
    { currency: 'GMD', currency_symbol: 'D', multiplier: 100, type: 'Paystack' },
    { currency: 'GNF', currency_symbol: 'Fr', multiplier: 1, type: 'Paystack' },
    { currency: 'GTQ', currency_symbol: 'Q', multiplier: 100, type: 'Paystack' },
    { currency: 'GYD', currency_symbol: '$', multiplier: 100, type: 'Paystack' },
    { currency: 'HKD', currency_symbol: '$', multiplier: 100, type: 'Paystack' },
    { currency: 'HNL', currency_symbol: 'L', multiplier: 100, type: 'Paystack' },
    { currency: 'HRK', currency_symbol: 'kn', multiplier: 100, type: 'Paystack' },
    { currency: 'HTG', currency_symbol: 'G', multiplier: 100, type: 'Paystack' },
    { currency: 'HUF', currency_symbol: 'Ft', multiplier: 100, type: 'Paystack' },
    { currency: 'IDR', currency_symbol: 'Rp', multiplier: 100, type: 'Paystack' },
    { currency: 'ILS', currency_symbol: 'ع.د', multiplier: 100, type: 'Paystack' },
    { currency: 'INR', currency_symbol: '₹', multiplier: 100, type: 'Paystack' },
    { currency: 'ISK', currency_symbol: 'kr', multiplier: 100, type: 'Paystack' },
    { currency: 'JMD', currency_symbol: '$', multiplier: 100, type: 'Paystack' },
    { currency: 'JPY', currency_symbol: '¥', multiplier: 1, type: 'Paystack' },
    { currency: 'KES', currency_symbol: 'Sh', multiplier: 100, type: 'Paystack' },
    { currency: 'KGS', currency_symbol: 'с', multiplier: 100, type: 'Paystack' },
    { currency: 'KHR', currency_symbol: '៛', multiplier: 100, type: 'Paystack' },
    { currency: 'KMF', currency_symbol: 'Fr', multiplier: 1, type: 'Paystack' },
    { currency: 'KRW', currency_symbol: '₩', multiplier: 1, type: 'Paystack' },
    { currency: 'KYD', currency_symbol: '$', multiplier: 100, type: 'Paystack' },
    { currency: 'KZT', currency_symbol: '₸', multiplier: 100, type: 'Paystack' },
    { currency: 'LAK', currency_symbol: '₭', multiplier: 100, type: 'Paystack' },
    { currency: 'LBP', currency_symbol: 'ل.ل', multiplier: 100, type: 'Paystack' },
    { currency: 'LKR', currency_symbol: 'Rs', multiplier: 100, type: 'Paystack' },
    { currency: 'LRD', currency_symbol: '$', multiplier: 100, type: 'Paystack' },
    { currency: 'LSL', currency_symbol: 'L', multiplier: 100, type: 'Paystack' },
    { currency: 'MAD', currency_symbol: 'د.م.', multiplier: 100, type: 'Paystack' },
    { currency: 'MDL', currency_symbol: 'L', multiplier: 100, type: 'Paystack' },
    { currency: 'MGA', currency_symbol: 'Ar', multiplier: 1, type: 'Paystack' },
    { currency: 'MKD', currency_symbol: 'ден', multiplier: 100, type: 'Paystack' },
    { currency: 'MMK', currency_symbol: 'Ks', multiplier: 100, type: 'Paystack' },
    { currency: 'MNT', currency_symbol: '₮', multiplier: 100, type: 'Paystack' },
    { currency: 'MOP', currency_symbol: 'P', multiplier: 100, type: 'Paystack' },
    { currency: 'MRO', currency_symbol: 'UM', multiplier: 100, type: 'Paystack' },
    { currency: 'MUR', currency_symbol: '₨', multiplier: 100, type: 'Paystack' },
    { currency: 'MVR', currency_symbol: '.ރ', multiplier: 100, type: 'Paystack' },
    { currency: 'MWK', currency_symbol: 'MK', multiplier: 100, type: 'Paystack' },
    { currency: 'MXN', currency_symbol: '$', multiplier: 100, type: 'Paystack' },
    { currency: 'MYR', currency_symbol: 'RM', multiplier: 100, type: 'Paystack' },
    { currency: 'MZN', currency_symbol: 'MT', multiplier: 100, type: 'Paystack' },
    { currency: 'NAD', currency_symbol: '$', multiplier: 100, type: 'Paystack' },
    { currency: 'NGN', currency_symbol: '₦', multiplier: 100, type: 'Paystack' },
    { currency: 'NIO', currency_symbol: 'C$', multiplier: 100, type: 'Paystack' },
    { currency: 'NOK', currency_symbol: 'kr', multiplier: 100, type: 'Paystack' },
    { currency: 'NPR', currency_symbol: '₨', multiplier: 100, type: 'Paystack' },
    { currency: 'NZD', currency_symbol: '$', multiplier: 100, type: 'Paystack' },
    { currency: 'PAB', currency_symbol: 'B/.', multiplier: 100, type: 'Paystack' },
    { currency: 'PEN', currency_symbol: 'S/.', multiplier: 100, type: 'Paystack' },
    { currency: 'PGK', currency_symbol: 'K', multiplier: 100, type: 'Paystack' },
    { currency: 'PHP', currency_symbol: '₱', multiplier: 100, type: 'Paystack' },
    { currency: 'PKR', currency_symbol: '₨', multiplier: 100, type: 'Paystack' },
    { currency: 'PLN', currency_symbol: 'zł', multiplier: 100, type: 'Paystack' },
    { currency: 'PYG', currency_symbol: '₲', multiplier: 1, type: 'Paystack' },
    { currency: 'QAR', currency_symbol: 'ر.ق', multiplier: 100, type: 'Paystack' },
    { currency: 'RON', currency_symbol: 'lei', multiplier: 100, type: 'Paystack' },
    { currency: 'RSD', currency_symbol: 'дин', multiplier: 100, type: 'Paystack' },
    { currency: 'RUB', currency_symbol: '₽', multiplier: 100, type: 'Paystack' },
    { currency: 'RWF', currency_symbol: 'Fr', multiplier: 1, type: 'Paystack' },
    { currency: 'SAR', currency_symbol: 'ر.س', multiplier: 100, type: 'Paystack' },
    { currency: 'SBD', currency_symbol: '$', multiplier: 100, type: 'Paystack' },
    { currency: 'SCR', currency_symbol: '₨', multiplier: 100, type: 'Paystack' },
    { currency: 'SEK', currency_symbol: 'kr', multiplier: 100, type: 'Paystack' },
    { currency: 'SGD', currency_symbol: '$', multiplier: 100, type: 'Paystack' },
    { currency: 'SHP', currency_symbol: '£', multiplier: 100, type: 'Paystack' },
    { currency: 'SLL', currency_symbol: 'Le', multiplier: 100, type: 'Paystack' },
    { currency: 'SOS', currency_symbol: 'Sh', multiplier: 100, type: 'Paystack' },
    { currency: 'SRD', currency_symbol: '$', multiplier: 100, type: 'Paystack' },
    { currency: 'STD', currency_symbol: 'Db', multiplier: 100, type: 'Paystack' },
    { currency: 'SZL', currency_symbol: 'L', multiplier: 100, type: 'Paystack' },
    { currency: 'THB', currency_symbol: '฿', multiplier: 100, type: 'Paystack' },
    { currency: 'TJS', currency_symbol: 'ЅМ', multiplier: 100, type: 'Paystack' },
    { currency: 'TOP', currency_symbol: 'T$', multiplier: 100, type: 'Paystack' },
    { currency: 'TRY', currency_symbol: '₺', multiplier: 100, type: 'Paystack' },
    { currency: 'TTD', currency_symbol: '$', multiplier: 100, type: 'Paystack' },
    { currency: 'TWD', currency_symbol: '$', multiplier: 100, type: 'Paystack' },
    { currency: 'TZS', currency_symbol: 'Sh', multiplier: 100, type: 'Paystack' },
    { currency: 'UAH', currency_symbol: '₴', multiplier: 100, type: 'Paystack' },
    { currency: 'UGX', currency_symbol: 'Sh', multiplier: 1, type: 'Paystack' },
    { currency: 'UYU', currency_symbol: '$', multiplier: 100, type: 'Paystack' },
    { currency: 'UZS', currency_symbol: 'сўм', multiplier: 100, type: 'Paystack' },
    { currency: 'VND', currency_symbol: '₫', multiplier: 1, type: 'Paystack' },
    { currency: 'VUV', currency_symbol: 'Vt', multiplier: 1, type: 'Paystack' },
    { currency: 'WST', currency_symbol: 'T', multiplier: 100, type: 'Paystack' },
    { currency: 'XAF', currency_symbol: 'Fr', multiplier: 1, type: 'Paystack' },
    { currency: 'XCD', currency_symbol: '$', multiplier: 100, type: 'Paystack' },
    { currency: 'XOF', currency_symbol: 'Fr', multiplier: 1, type: 'Paystack' },
    { currency: 'XPF', currency_symbol: '₣', multiplier: 1, type: 'Paystack' },
    { currency: 'YER', currency_symbol: '﷼', multiplier: 100, type: 'Paystack' },
    { currency: 'ZAR', currency_symbol: 'Rs', multiplier: 100, type: 'Paystack' },
    { currency: 'ZMW', currency_symbol: 'ZK', multiplier: 100, type: 'Paystack' }
  ]
  
  export const paypalCurrencies = [
    { currency: 'AUD', currency_symbol: '$', type: 'PAYPAL' },
    { currency: 'BRL', currency_symbol: 'R$', type: 'PAYPAL' },
    { currency: 'CAD', currency_symbol: '$', type: 'PAYPAL' },
    { currency: 'CZK', currency_symbol: 'Kč', type: 'PAYPAL' },
    { currency: 'DKK', currency_symbol: 'kr', type: 'PAYPAL' },
    { currency: 'EUR', currency_symbol: '€', type: 'PAYPAL' },
    { currency: 'HKD', currency_symbol: '$', type: 'PAYPAL' },
    { currency: 'HUF', currency_symbol: 'Ft', type: 'PAYPAL' },
    { currency: 'INR', currency_symbol: '₹', type: 'PAYPAL' },
    { currency: 'ILS', currency_symbol: 'ع.د', type: 'PAYPAL' },
    { currency: 'JPY', currency_symbol: '¥', type: 'PAYPAL' },
    { currency: 'MYR', currency_symbol: 'RM', type: 'PAYPAL' },
    { currency: 'MXN', currency_symbol: '$', type: 'PAYPAL' },
    { currency: 'TWD', currency_symbol: '$', type: 'PAYPAL' },
    { currency: 'NZD', currency_symbol: '$', type: 'PAYPAL' },
    { currency: 'NOK', currency_symbol: 'kr', type: 'PAYPAL' },
    { currency: 'PHP', currency_symbol: '₱', type: 'PAYPAL' },
    { currency: 'PLN', currency_symbol: 'zł', type: 'PAYPAL' },
    { currency: 'GBP', currency_symbol: '£', type: 'PAYPAL' },
    { currency: 'RUB', currency_symbol: '₽', type: 'PAYPAL' },
    { currency: 'SGD', currency_symbol: '$', type: 'PAYPAL' },
    { currency: 'SEK', currency_symbol: 'kr', type: 'PAYPAL' },
    { currency: 'CHF', currency_symbol: 'Fr', type: 'PAYPAL' },
    { currency: 'THB', currency_symbol: '฿', type: 'PAYPAL' },
    { currency: 'USD', currency_symbol: '$', type: 'PAYPAL' }
  ]
  